- name: Clone Ubuntu Template to VM
  community.proxmox.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ pve_node }}"
    name: "{{ inventory_hostname }}"
    clone: "{{ template_name }}"
    full: true
    net:
      net0: "virtio,bridge=vmbr0"
      net1: "virtio,bridge={{ storage_bridge }}" # This handles your SDN split!
    ipconfig:
      ipconfig0: "ip={{ mgmt_ip }}/24,gw={{ mgmt_gw }}"
      ipconfig1: "ip={{ storage_ip }}/24"
    sshkeys: "{{ ssh_public_key }}"
    state: started